version: '3.5'

services:

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:inception
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - ../.env
    networks:
     - inception

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx:inception
    ports:
      - '443:443'
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    env_file:
      - ../.env
    networks:
      - inception


  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:inception
    ports:
      - '9000:9000'
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wordpress:/var/www/html
    env_file:
      - ../.env
    networks:
      - inception
  
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    image: adminer:inception
    ports:
      - '8080:8080'
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    image: redis:inception
    depends_on:
      - wordpress
    restart: always
    volumes:
      - wordpress_v:/var/www/html
    networks:
      - inception

  cadvisor:
    build: ./requirements/bonus/cadvisor
    image: cadvisor
    container_name: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
        - inception
    ports:
      - '7000:7000'

  static_ws:
    build: ./requirements/bonus/static_ws
    container_name: static_ws
    image: static_ws
    restart: always
    ports:
      - '80:80'
    networks:
      - inception

  

volumes:
  wordpress:
    driver: local
    driver_opts:
      device: /home/hbouqssi/data/wp
      o: bind
      type: none
  mariadb:
    driver: local
    driver_opts:
      device: /home/hbouqssi/data/db
      o: bind
      type: none

networks:
  inception:
   name: inception
