version: '3.5'

services:

  mariadb:
    build: ./services/MariaDB
    container_name: mariadb
    ports:
      - 3306:3306
    restart: always
    volumes:
      - mariadb_v:/var/lib/mysql

  nginx:
    build: /home/jugurtha/Desktop/Inception/services/NGINX
    container_name: nginx
    ports:
      - 443:443
    restart: always

  wordpress:
    build: /home/jugurtha/Desktop/Inception/services/Wordpress
    container_name: wordpress
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wordpress_v:/var/www/html

  

volumes:
  wordpress_v:
    driver: local
    driver_opts:
      device: /home/jugurtha/Desktop/data/wp
      o: bind
      type: none
  mariadb_v:
    driver: local
    driver_opts:
      device: /home/jugurtha/Desktop/data/mr
      o: bind
      type: none

# networks:
#   inception:
#     name: inception
#     driver: bridge
