version: '3.5'

services:

  mariadb:
    build: ./services/MariaDB
    container_name: mariadb
    image: mariadb:inception
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mariadb_v:/var/lib/mysql
    env_file:
      - .env
    networks:
     - inception

  nginx:
    build: ./services/NGINX
    container_name: nginx
    image: nginx:inception
    ports:
      - 443:443
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress_v:/var/www/html
    env_file:
      - .env
    networks:
      - inception


  wordpress:
    build: ./services/Wordpress
    container_name: wordpress
    image: wordpress:inception
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wordpress_v:/var/www/html
    env_file:
      - .env
    networks:
      - inception
  
  adminer:
    build: ./services/adminer
    container_name: adminer
    image: adminer:inception
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception

  redis:
    build: ./services/redis
    container_name: redis
    image: redis:inception
    depends_on:
      - wordpress
    restart: always
    volumes:
      - wordpress_v:/var/www/html
    networks:
      - inception
    
  cadvisor:
    build: ./services/cadvisor
    container_name: cadvisor
    images: cadvisor:inception
    restart: always
    ports:
      - 8080:8080
    networkd:
      - inception

  

volumes:
  wordpress_v:
    driver: local
    driver_opts:
      device: /Users/hbouqssi/Desktop/data/Wp
      o: bind
      type: none
  mariadb_v:
    driver: local
    driver_opts:
      device: /Users/hbouqssi/Desktop/data/Db
      o: bind
      type: none

networks:
  inception:
   name: inception
