CREATE DATABASE IF NOT EXISTS wordpress ;
CREATE USER IF NOT EXISTS 'hamza'@'%' IDENTIFIED BY 'hamza123' ;
GRANT ALL PRIVILEGES ON wordpress.* TO 'hamza'@'%' ;
ALTER USER 'root'@'localhost' IDENTIFIED BY '12345' ;
FLUSH PRIVILEGES;
